[package]
name = "exec"
version = "0.1.0"
authors = ["Tom <tom@contextfree.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
futures = "0.3"

[[bin]]
name = "count"
path = "count.rs"
