[package]
name = "exec"
version = "0.1.0"
authors = ["Tom <tom@contextfree.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "exec"
path = "exec.rs"
