[package]
name = "exec"
version = "0.1.0"
authors = ["Tom <tom@contextfree.info>"]
edition = "2018"

[dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }
chrono = "0.4"
futures = "0.3"

[[bin]]
name = "count"
path = "count.rs"
